version: '3'

services:
  bind9:
    container_name: dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind:/etc/bind
    restart: unless-stopped
    networks:
      - app-network


  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      - app-network


  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
      - ./www:/usr/share/nginx/html
    volumes_from:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - app-network

  php:
    image: php:8.0-fpm
    volumes:
      - ./html/hosting-laplata.com.ar:/var/www/html/hosting-laplata.com.ar
      - ./html/hosting-laplata.xyz:/usr/share/nginx/html/
    restart: unless-stopped
    networks:
      - app-network


  node:
    image: node:latest
    volumes:
      - ./nodejs/:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run build && npx serve@latest out -l 3000"
    restart: 'no'

  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network


  app1:
    image: nginx:latest
    volumes:
      - ./nodejs/out:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=hosting-laplata.com.ar
      - LETSENCRYPT_HOST=hosting-laplata.com.ar
      - LETSENCRYPT_EMAIL=sergioscardigno@gmail.com
    expose:
      - "80"
    depends_on:
      - php
      - node
    networks:
      - app-network

  app2:
    image: richarvey/nginx-php-fpm:latest
    volumes:
      - ./html/hosting-laplata.xyz:/var/www/html/
    environment:
      - VIRTUAL_HOST=hosting-laplata.xyz
      - LETSENCRYPT_HOST=hosting-laplata.xyz
      - LETSENCRYPT_EMAIL=sergioscardigno@gmail.com
    expose:
      - "80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
